ssh: {}
hotkeys:
  toggle-window: []
terminal:
  colorScheme:
    name: Material
    foreground: '#232322'
    background: '#eaeaea'
    cursor: '#16afca'
    colors:
      - '#212121'
      - '#b7141f'
      - '#457b24'
      - '#f6981e'
      - '#134eb2'
      - '#560088'
      - '#0e717c'
      - '#efefef'
      - '#424242'
      - '#e83b3f'
      - '#7aba3a'
      - '#ffea2e'
      - '#54a4f3'
      - '#aa4dbc'
      - '#26bbd1'
      - '#d9d9d9'
  persistence: null
  background: colorScheme
  font: Calling Code
  cursor: beam
  autoOpen: true
  fontSize: 16
appearance:
  frame: thin
  tabsLocation: top
  theme: Compact
pluginBlacklist:
  - ssh
  - shell-selector
